[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_RECAPTCHASITEKEY = "6LcFFtQrAAAAAA_diyxm9O8M6TqIxH875_AR_YW9"

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "https://sea-of-mountains-backend.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # UPDATED Content-Security-Policy to fix reCAPTCHA and external resource connection errors in production.
    Content-Security-Policy = """
      default-src 'self' blob: data:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: https://www.google.com https://www.gstatic.com;
      connect-src 'self' https://sea-of-mountains-backend.onrender.com https://ingesteer.services-prod.nsvcs.net https://www.google.com https://www.gstatic.com;
      frame-src 'self' https://www.google.com https://www.gstatic.com;
    """

# Cache control
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"